### PR TITLE
Hide Shortcut Button in product page

### PR DESCRIPTION
**Pull request by miguelbarrientos**
Hide Shorcut button when Catalog mode is activated, the change is on the line 62

### CODE REVIEW

**Comment by Quetzacoalt91** [comment]
Hi @miguelbarrientos,

This PR is not complete, because the button also appear at the bottom of the page, as you can see on the following screenshot:
screen shot 2015-05-04 at 10 22 04

Best regards

**Comment by miguelbarrientos** [comment]
Hi Thomas,

Ok, thanks, I'll fix it,

Regards,


El Monday, May 4, 2015, Thomas N <notifications@github.com> escribió:

> Hi @miguelbarrientos <https://github.com/miguelbarrientos>,
>
> This PR is not complete, because the button also appear at the bottom of
> the page, as you can see on the following screenshot:
> [image: screen shot 2015-05-04 at 10 22 04]
> <https://cloud.githubusercontent.com/assets/6768917/7450643/8f26b696-f247-11e4-8c7a-4b0148eaa901.png>
>
> Best regards
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PrestaShop/paypalmx/pull/9#issuecomment-98631074>.
>


-- 


*Ing. Miguel Barrientos*
Project Manager

Pengo Stores
Apasionados del e-commerce
www.pengostores.com
Oficina: +52 55 9628-2118
Móvil: +52 1 55 4678-6845

**Comment by miguelbarrientos** [comment]
Hi Thomas,
The update has been made,
Best,

**Comment by Quetzacoalt91** [comment]
Hi @miguelbarrientos,

Thanks, your PR has just been merged and the changes should be available from tomorrow.

Best regards

**Pull request merged**
