### PR TITLE
Fixes formatting by removing some css

### PR DESCRIPTION
**Pull request by rfeathers**
CSS is best applied in CSS, after all

### CODE REVIEW

**Comment by gaillafr** [comment]
Hi @rfeathers, whatis the purpose of this PR?
Thank you, kind regards.

**Comment by rfeathers** [comment]
The PR addresses floating issue in CSS for the paypal button

~R~

Ron Feathers
Technology Leadership Program – Class of 2015

eBay Inc.
rfeathers@paypal.com<mailto:rfeathers@paypal.com>
m: 510 468 6117
Skype: webfeathers
Adobe Connect: http://myroom-na.adobeconnect.com/feathers
[cid:5FE4CCDC-0D32-4025-8242-4C088A1E6EDC]

**Comment by tchauviere** [comment]
Hi @rfeathers,

Your PR is Ok, except for one little PHP Notice I found on 1.6.0.11:
```php
PHP Notice:  Undefined index: PAYMENTREQUEST_0_SHIPTOSTATE in /var/www/prestashop_16011/modules/paypalmx/controllers/front/expresscheckout.php on line 205
```

I'll merge this PR as soon as this notice is fixed.

Thank you!

Best regards,

**Comment by rfeathers** [comment]
Thank you for the note.
New commit added that checks isset for the value

~R~

Ron Feathers
Technology Leadership Program – Class of 2015

eBay Inc.
rfeathers@paypal.com<mailto:rfeathers@paypal.com>
m: 510 468 6117
Skype: webfeathers
Adobe Connect: http://myroom-na.adobeconnect.com/feathers
[cid:5062506B-37DE-4B49-B2B8-2AAEFF360F67]

**Comment by rfeathers** [comment]
New commit added for this PR.

**Comment by rfeathers** [comment]
Thank you for all of your help, guys!
This latest check in fixes the broken checkout flow when going directly through the PS cart.

**Pull request merged**
